INSERT INTO [dbo].[States] 
(StateName, Population, FlagDescription, StateFlower, StateBird, Colors, LargestCities, StateCapital, MedianIncome, ComputerJobsPercent) 
VALUES
('Alabama', 5024279, 'A crimson cross on a white field', 'Camellia', 'Yellowhammer', 'Red, White', 'Birmingham, Montgomery, Mobile', 'Montgomery', 56762, 3.2),
('Alaska', 733391, 'Big Dipper and North Star on a blue field', 'Forget-me-not', 'Willow Ptarmigan', 'Blue, Gold', 'Anchorage, Fairbanks, Juneau', 'Juneau', 77640, 4.1),
('Arizona', 7151502, 'Red and yellow rays with a blue bottom', 'Saguaro Cactus Blossom', 'Cactus Wren', 'Blue, Red, Yellow', 'Phoenix, Tucson, Mesa', 'Phoenix', 61862, 5.3),
('Arkansas', 3011524, 'Diamond shape with a blue border and 25 stars', 'Apple Blossom', 'Mockingbird', 'Red, White, Blue', 'Little Rock, Fort Smith, Fayetteville', 'Little Rock', 49789, 2.8),
('California', 39538223, 'Bear with a red star on a white field', 'California Poppy', 'California Quail', 'Blue, Gold', 'Los Angeles, San Diego, San Jose', 'Sacramento', 81367, 7.4),
('Colorado', 5773714, 'C with a gold disk on a blue and white background', 'Rocky Mountain Columbine', 'Lark Bunting', 'Blue, White, Red, Gold', 'Denver, Colorado Springs, Aurora', 'Denver', 75795, 6.1),
('Connecticut', 3605944, 'Blue shield with three grapevines', 'Mountain Laurel', 'American Robin', 'Blue, Gold', 'Bridgeport, New Haven, Stamford', 'Hartford', 79887, 6.8),
('Delaware', 989948, 'Buff-colored diamond with a colonial farmer and soldier', 'Peach Blossom', 'Delaware Blue Hen', 'Buff, Blue', 'Wilmington, Dover, Newark', 'Dover', 69887, 4.7),
('Florida', 21538187, 'A red St. Andrew’s Cross on a white field with state seal', 'Orange Blossom', 'Northern Mockingbird', 'Orange, Red, White', 'Jacksonville, Miami, Tampa', 'Tallahassee', 57680, 5.9),
('Georgia', 10711908, 'Three pillars supporting an arch with the motto "Wisdom, Justice, Moderation"', 'Cherokee Rose', 'Brown Thrasher', 'Red, White, Gold', 'Atlanta, Augusta, Columbus', 'Atlanta', 61697, 4.9),
('Hawaii', 1455271, 'Union Jack and eight alternating white, red, and blue stripes', 'Hibiscus', 'Nene', 'Red, White, Blue', 'Honolulu, Hilo, Kailua', 'Honolulu', 81812, 4.3),
('Idaho', 1839106, 'State seal on a blue field', 'Syringa', 'Mountain Bluebird', 'Blue, Gold', 'Boise, Meridian, Nampa', 'Boise', 60136, 3.7),
('Illinois', 12812508, 'Bald eagle with shield and banner', 'Violet', 'Northern Cardinal', 'Blue, White', 'Chicago, Aurora, Naperville', 'Springfield', 70255, 5.8),
('Indiana', 6785528, 'Gold torch with stars on a blue field', 'Peony', 'Northern Cardinal', 'Blue, Gold', 'Indianapolis, Fort Wayne, Evansville', 'Indianapolis', 60499, 4.5),
('Iowa', 3190369, 'Bald eagle holding a ribbon with state motto', 'Wild Rose', 'Eastern Goldfinch', 'Red, White, Blue', 'Des Moines, Cedar Rapids, Davenport', 'Des Moines', 60547, 4.2),
('Kansas', 2937880, 'State seal with a rising sun and 34 stars', 'Sunflower', 'Western Meadowlark', 'Blue, Gold', 'Wichita, Overland Park, Kansas City', 'Topeka', 58720, 3.9),
('Kentucky', 4505836, 'State seal with two figures embracing', 'Goldenrod', 'Northern Cardinal', 'Blue, Gold', 'Louisville, Lexington, Bowling Green', 'Frankfort', 52584, 3.4),
('Louisiana', 4657757, 'Pelican feeding its young with its blood', 'Magnolia', 'Brown Pelican', 'Blue, Gold, White', 'New Orleans, Baton Rouge, Shreveport', 'Baton Rouge', 50130, 2.9),
('Maine', 1362359, 'Coat of arms with a moose and pine tree', 'White Pine Cone and Tassel', 'Chickadee', 'Blue, Gold', 'Portland, Lewiston, Bangor', 'Augusta', 60823, 3.1),
('Maryland', 6177224, 'Quartered black and gold with red and white crosses', 'Black-Eyed Susan', 'Baltimore Oriole', 'Red, White, Black, Gold', 'Baltimore, Columbia, Germantown', 'Annapolis', 87063, 7.1),
('Massachusetts', 7029917, 'Blue shield with an Algonquin Native American', 'Mayflower', 'Black-Capped Chickadee', 'Blue, White, Gold', 'Boston, Worcester, Springfield', 'Boston', 89810, 8.5),
('Michigan', 10077331, 'Coat of arms with an elk and moose', 'Apple Blossom', 'American Robin', 'Blue, Gold, Red', 'Detroit, Grand Rapids, Warren', 'Lansing', 60255, 5.7),
('Minnesota', 5706494, 'State seal with a farmer and an Indian on horseback', 'Pink and White Lady Slipper', 'Common Loon', 'Blue, Gold, Red', 'Minneapolis, St. Paul, Rochester', 'St. Paul', 74101, 6.2),
('Mississippi', 2961279, 'Vertical blue, gold, and red stripes with a magnolia', 'Magnolia', 'Northern Mockingbird', 'Red, White, Blue', 'Jackson, Gulfport, Southaven', 'Jackson', 46235, 2.7),
('Missouri', 6154913, 'Coat of arms with two grizzly bears', 'Hawthorn', 'Eastern Bluebird', 'Blue, Red, White', 'Kansas City, St. Louis, Springfield', 'Jefferson City', 55661, 4.1),
('Montana', 1084225, 'State seal with mountains and a river', 'Bitterroot', 'Western Meadowlark', 'Blue, Gold', 'Billings, Missoula, Great Falls', 'Helena', 57916, 3.5),
('Nebraska', 1961504, 'State seal with a steamboat and train', 'Goldenrod', 'Western Meadowlark', 'Blue, Gold', 'Omaha, Lincoln, Bellevue', 'Lincoln', 63015, 4.0),
('Nevada', 3104614, 'Silver star with sagebrush wreath', 'Sagebrush', 'Mountain Bluebird', 'Blue, Silver', 'Las Vegas, Henderson, Reno', 'Carson City', 60887, 5.4),
('New Hampshire', 1377529, 'State seal with a ship', 'Purple Lilac', 'Purple Finch', 'Blue, Gold, Red', 'Manchester, Nashua, Concord', 'Concord', 77494, 6.8),
('New Jersey', 9288994, 'Coat of arms with a horse and goddesses', 'Violet', 'Eastern Goldfinch', 'Blue, Buff', 'Newark, Jersey City, Paterson', 'Trenton', 85745, 8.1),
('New Mexico', 2117522, 'Red Zia sun symbol on a yellow field', 'Yucca', 'Greater Roadrunner', 'Red, Yellow', 'Albuquerque, Las Cruces, Rio Rancho', 'Santa Fe', 52769, 3.2),
('New York', 20201249, 'Coat of arms with Lady Liberty and Justice', 'Rose', 'Eastern Bluebird', 'Blue, Gold, White', 'New York City, Buffalo, Rochester', 'Albany', 76237, 7.9),
('North Carolina', 10439388, 'Red and blue bars with white stars and initials', 'Dogwood', 'Northern Cardinal', 'Red, White, Blue', 'Charlotte, Raleigh, Greensboro', 'Raleigh', 57799, 5.2),
('North Dakota', 779094, 'Bald eagle with a banner', 'Prairie Rose', 'Western Meadowlark', 'Blue, Gold, Red', 'Fargo, Bismarck, Grand Forks', 'Bismarck', 64287, 3.6),
('Ohio', 11799448, 'Swallowtail flag with red, white, and blue', 'Scarlet Carnation', 'Northern Cardinal', 'Red, White, Blue', 'Columbus, Cleveland, Cincinnati', 'Columbus', 63717, 5.5),
('Oklahoma', 3959353, 'Osage shield with olive branch and calumet', 'Mistletoe', 'Scissor-tailed Flycatcher', 'Blue, Gold, Red', 'Oklahoma City, Tulsa, Norman', 'Oklahoma City', 54434, 3.8),
('Oregon', 4237256, 'State seal with a beaver', 'Oregon Grape', 'Western Meadowlark', 'Blue, Gold', 'Portland, Salem, Eugene', 'Salem', 67293, 5.9),
('Pennsylvania', 13002700, 'Coat of arms with black horses', 'Mountain Laurel', 'Ruffed Grouse', 'Blue, Gold', 'Philadelphia, Pittsburgh, Allentown', 'Harrisburg', 67762, 6.1),
('Rhode Island', 1097379, 'Anchor with "Hope" banner', 'Violet', 'Rhode Island Red', 'Blue, Gold, White', 'Providence, Warwick, Cranston', 'Providence', 73257, 6.6),
('South Carolina', 5118425, 'Palmetto tree and crescent on blue field', 'Yellow Jessamine', 'Carolina Wren', 'Blue, White', 'Charleston, Columbia, North Charleston', 'Columbia', 52259, 3.5),
('South Dakota', 886667, 'State seal with a riverboat and Mount Rushmore', 'Pasque Flower', 'Ring-Necked Pheasant', 'Blue, Gold', 'Sioux Falls, Rapid City, Aberdeen', 'Pierre', 62239, 3.3),
('Tennessee', 6916897, 'Three white stars on a blue circle', 'Iris', 'Northern Mockingbird', 'Red, White, Blue', 'Nashville, Memphis, Knoxville', 'Nashville', 58442, 4.2),
('Texas', 29145505, 'Single white star on a blue field', 'Bluebonnet', 'Northern Mockingbird', 'Blue, White, Red', 'Houston, San Antonio, Dallas', 'Austin', 64134, 6.7),
('Utah', 3271616, 'Beehive with sego lilies and an eagle', 'Sego Lily', 'California Gull', 'Blue, Gold', 'Salt Lake City, West Valley City, Provo', 'Salt Lake City', 76156, 6.0),
('Vermont', 643077, 'Coat of arms with a deer and pine tree', 'Red Clover', 'Hermit Thrush', 'Blue, Gold, Green', 'Burlington, South Burlington, Rutland', 'Montpelier', 70212, 5.1),
('Virginia', 8631393, 'Roman goddess Virtus defeating a tyrant', 'American Dogwood', 'Northern Cardinal', 'Blue, Gold, Red', 'Virginia Beach, Norfolk, Chesapeake', 'Richmond', 76298, 6.4),
('Washington', 7705281, 'Portrait of George Washington on green field', 'Coast Rhododendron', 'Willow Goldfinch', 'Green, Gold', 'Seattle, Spokane, Tacoma', 'Olympia', 78934, 7.2),
('West Virginia', 1793716, 'Coat of arms with rifles and a farmer', 'Rhododendron', 'Northern Cardinal', 'Blue, Gold', 'Charleston, Huntington, Morgantown', 'Charleston', 48850, 3.0),
('Wisconsin', 5893718, 'Coat of arms with a sailor and miner', 'Wood Violet', 'American Robin', 'Blue, Gold', 'Milwaukee, Madison, Green Bay', 'Madison', 67099, 5.3),
('Wyoming', 576851, 'Buffalo silhouette with state seal', 'Indian Paintbrush', 'Western Meadowlark', 'Blue, Gold', 'Cheyenne, Casper, Laramie', 'Cheyenne', 64480, 4.0);;

